name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Cette ligne récupère les fichiers du repository Git
      - name: Run Python script
        run: python job.py
      - name: Run tests
        run: pytest test_job.py
