name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false # Changez à 'true' si vous voulez pousser l'image
          tags: your-registry/your-image-name:latest
          build-args: |
            # Si nécessaire, vous pouvez ajouter des arguments de build ici
      - name: Push Docker image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true # Changez à 'false' si vous ne voulez pas pousser l'image
          tags: your-registry/your-image-name:latest
          build-args: |
            # Si nécessaire, vous pouvez ajouter des arguments de build ici
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
